gridpulse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "../../data/gold/gridpulse.duckdb"
      threads: 4
      extensions: [icu]
    ci:
      type: duckdb
      path: ":memory:"
      threads: 2
